# Generated by Django 5.2.4 on 2025-07-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasedb',
            options={'ordering': ['cita'], 'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.AddField(
            model_name='autordb',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='frasedb',
            name='autor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.autordb'),
        ),
    ]
