# Generated by Django 5.2.4 on 2025-07-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_frasedb_options_autordb_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eps', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FondoCesantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo_cesantias', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FondoPensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo_pensiones', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JefeDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=15)),
                ('lugar_expedicion', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_celular', models.CharField(max_length=13)),
                ('numero_whatsapp', models.CharField(max_length=13)),
                ('correo_electronico', models.CharField(max_length=120)),
                ('direccion_residencia', models.CharField(max_length=255)),
                ('localidad_residencia', models.CharField(max_length=50)),
                ('barrio_residencia', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('rh', models.CharField(max_length=3)),
                ('estado_civil', models.CharField(max_length=15)),
                ('trabajo_previo_empresa', models.BooleanField()),
                ('motivo_retiro', models.CharField(max_length=50)),
                ('tipo_contrato', models.CharField(max_length=20)),
                ('sueldo', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('parentesco_familiar', models.CharField(max_length=20)),
                ('nombre_completo_familiar', models.CharField(max_length=120)),
                ('numero_celular_familiar', models.CharField(max_length=13)),
                ('archivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.archivos')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.cargo')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.eps')),
                ('fondo_cesantias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.fondocesantias')),
                ('fondo_pensiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.fondopensiones')),
                ('jefe_directo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.jefedirecto')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(max_length=40)),
                ('anio_finalizacion', models.DateField()),
                ('estudia_actualmente', models.BooleanField()),
                ('titulo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo_hijo', models.CharField(max_length=70)),
                ('fecha_nacimiento_hijo', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosDePlataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_plataforma_1', models.CharField(max_length=50)),
                ('usuario_plataforma_2', models.CharField(max_length=50)),
                ('usuario_plataforma_3', models.CharField(max_length=50)),
                ('usuario_plataforma_4', models.CharField(max_length=50)),
                ('usuario_plataforma_5', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.empleado')),
            ],
        ),
    ]
