# Generated by Django 5.2.4 on 2025-07-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_fondocesantias_archivo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FondoCesantia',
            new_name='Archivos',
        ),
        migrations.RenameModel(
            old_name='FondoPension',
            new_name='FondoCesantias',
        ),
        migrations.RenameModel(
            old_name='Archivo',
            new_name='FondoPensiones',
        ),
        migrations.RenameModel(
            old_name='UsuarioDePlataforma',
            new_name='UsuariosDePlataformas',
        ),
        migrations.RenameField(
            model_name='archivos',
            old_name='nombre',
            new_name='nombre_archivo',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='nombre',
            new_name='nombre_area',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='nombre',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fondo_cesantia',
            new_name='archivos',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fondo_pension',
            new_name='fondo_cesantias',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='archivo',
            new_name='fondo_pensiones',
        ),
        migrations.RenameField(
            model_name='eps',
            old_name='nombre',
            new_name='nombre_eps',
        ),
        migrations.RenameField(
            model_name='fondocesantias',
            old_name='nombre',
            new_name='nombre_fondo_cesantias',
        ),
        migrations.RenameField(
            model_name='fondopensiones',
            old_name='nombre',
            new_name='nombre_fondo_pensiones',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_hijo',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='nombre_completo',
            new_name='nombre_completo_hijo',
        ),
        migrations.RenameField(
            model_name='jefedirecto',
            old_name='empleado_id',
            new_name='id_empleado',
        ),
        migrations.RenameField(
            model_name='usuariosdeplataformas',
            old_name='usuario_1',
            new_name='usuario_plataforma_1',
        ),
        migrations.RenameField(
            model_name='usuariosdeplataformas',
            old_name='usuario_2',
            new_name='usuario_plataforma_2',
        ),
        migrations.RenameField(
            model_name='usuariosdeplataformas',
            old_name='usuario_3',
            new_name='usuario_plataforma_3',
        ),
        migrations.RenameField(
            model_name='usuariosdeplataformas',
            old_name='usuario_4',
            new_name='usuario_plataforma_4',
        ),
        migrations.RenameField(
            model_name='usuariosdeplataformas',
            old_name='usuario_5',
            new_name='usuario_plataforma_5',
        ),
    ]
