# Generated by Django 5.2.4 on 2025-07-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_rename_fondocesantia_archivos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
        migrations.RenameModel(
            old_name='FondoPensiones',
            new_name='FondoCesantia',
        ),
        migrations.RenameModel(
            old_name='FondoCesantias',
            new_name='FondoPension',
        ),
        migrations.RenameModel(
            old_name='UsuariosDePlataformas',
            new_name='UsuarioDePlataforma',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='nombre_archivo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='nombre_area',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='cargo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='archivos',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fondo_pensiones',
            new_name='fondo_cesantia',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fondo_cesantias',
            new_name='fondo_pension',
        ),
        migrations.RenameField(
            model_name='eps',
            old_name='nombre_eps',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='fondocesantia',
            old_name='nombre_fondo_pensiones',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='fondopension',
            old_name='nombre_fondo_cesantias',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='fecha_nacimiento_hijo',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='nombre_completo_hijo',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='jefedirecto',
            old_name='id_empleado',
            new_name='empleado_id',
        ),
        migrations.RenameField(
            model_name='usuariodeplataforma',
            old_name='usuario_plataforma_1',
            new_name='usuario_1',
        ),
        migrations.RenameField(
            model_name='usuariodeplataforma',
            old_name='usuario_plataforma_2',
            new_name='usuario_2',
        ),
        migrations.RenameField(
            model_name='usuariodeplataforma',
            old_name='usuario_plataforma_3',
            new_name='usuario_3',
        ),
        migrations.RenameField(
            model_name='usuariodeplataforma',
            old_name='usuario_plataforma_4',
            new_name='usuario_4',
        ),
        migrations.RenameField(
            model_name='usuariodeplataforma',
            old_name='usuario_plataforma_5',
            new_name='usuario_5',
        ),
    ]
