# Generated by Django 5.2.4 on 2025-07-18 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_rename_fondocesantia_archivos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'ordering': ['nombre_archivo'], 'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['cargo'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['nivel_academico', 'titulo'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='eps',
            options={'ordering': ['nombre_eps'], 'verbose_name': 'EPS', 'verbose_name_plural': 'EPS'},
        ),
        migrations.AlterModelOptions(
            name='fondocesantias',
            options={'ordering': ['nombre_fondo_cesantias'], 'verbose_name': 'Fondo de Cesantías', 'verbose_name_plural': 'Fondos de Cesantías'},
        ),
        migrations.AlterModelOptions(
            name='fondopensiones',
            options={'ordering': ['nombre_fondo_pensiones'], 'verbose_name': 'Fondo de Pensiones', 'verbose_name_plural': 'Fondos de Pensiones'},
        ),
        migrations.AlterModelOptions(
            name='hijo',
            options={'ordering': ['nombre_completo_hijo'], 'verbose_name': 'Hijo', 'verbose_name_plural': 'Hijos'},
        ),
        migrations.AlterModelOptions(
            name='jefedirecto',
            options={'ordering': ['id_empleado'], 'verbose_name': 'Jefe Directo', 'verbose_name_plural': 'Jefes Directos'},
        ),
        migrations.AlterModelOptions(
            name='usuariosdeplataformas',
            options={'ordering': ['empleado'], 'verbose_name': 'Usuarios de Plataformas', 'verbose_name_plural': 'Usuarios de Plataformas'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='archivos',
        ),
        migrations.AddField(
            model_name='archivos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archivos',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='area',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='area',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='area',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cargo',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='educacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='educacion',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='educacion',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eps',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eps',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eps',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fondocesantias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fondocesantias',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fondocesantias',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fondopensiones',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fondopensiones',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fondopensiones',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hijo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hijo',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hijo',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jefedirecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jefedirecto',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jefedirecto',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuariosdeplataformas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariosdeplataformas',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuariosdeplataformas',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='barrio_residencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='lugar_expedicion',
            field=models.CharField(max_length=100),
        ),
    ]
