# Generated by Django 5.2.4 on 2025-07-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_archivos_options_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='eps',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='fondocesantias',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='fondopensiones',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='hijo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuariosdeplataformas',
            name='activo',
        ),
    ]
