# Generated by Django 5.2.4 on 2025-07-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_remove_archivos_activo_remove_cargo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='App1.empleado'),
        ),
    ]
