# Generated by Django 5.2.4 on 2025-07-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_archivos_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='empleado',
        ),
        migrations.AddField(
            model_name='archivos',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='App1.empleado'),
        ),
    ]
