# Generated by Django 5.2.4 on 2025-07-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_remove_archivos_empleado_archivos_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='App1.empleado'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='id_empleado',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_empleado'),
        ),
    ]
