# Generated by Django 5.2.4 on 2025-07-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_archivos_empleado_alter_archivos_id_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='id_empleado',
        ),
    ]
