# Generated by Django 5.2.4 on 2025-07-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_remove_archivos_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eps',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fondocesantias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fondopensiones',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.area'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.eps'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fondo_cesantias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.fondocesantias'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fondo_pensiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.fondopensiones'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.jefedirecto'),
        ),
    ]
