# Generated by Django 5.2.4 on 2025-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_archivos_activo_cargo_activo_eps_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_jefe',
            field=models.BooleanField(default=False),
        ),
    ]
