# Generated by Django 5.2.4 on 2025-07-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_remove_empleado_es_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='activo',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App1.jefedirecto'),
        ),
    ]
