# Generated by Django 5.2.4 on 2025-07-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_remove_archivos_activo_alter_empleado_jefe_directo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jefedirecto',
            options={'ordering': ['empleado'], 'verbose_name': 'Jefe Directo', 'verbose_name_plural': 'Jefes Directos'},
        ),
        migrations.RemoveField(
            model_name='jefedirecto',
            name='id_empleado',
        ),
        migrations.AddField(
            model_name='jefedirecto',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='es_jefe_directo', to='App1.empleado'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='App1.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados_a_cargo', to='App1.jefedirecto'),
        ),
    ]
