# Generated by Django 5.2.4 on 2025-07-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_alter_jefedirecto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='eps',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='fondocesantias',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='fondopensiones',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='jefedirecto',
            name='activo',
        ),
    ]
