# Generated by Django 5.2.4 on 2025-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_remove_area_activo_remove_cargo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='cargo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='eps',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='fondocesantias',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='fondopensiones',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='jefedirecto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
