# Generated by Django 5.2.4 on 2025-07-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0020_area_estado_cargo_estado_empleado_estado_eps_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='estudia_actualmente',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='jornada',
            field=models.CharField(choices=[('diurno', 'DIURNO'), ('nocturno', 'NOCTURNO'), ('virtual', 'VIRTUAL'), ('fin_de_semana', 'FIN DE SEMANA'), ('no_aplica', 'NO APLICA')], default='diurno', max_length=100),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='nivel_academico',
            field=models.CharField(choices=[('bachiller', 'BACHILLER'), ('tecnico', 'TÉCNICO'), ('tecnologo', 'TECNÓLOGO'), ('profesional', 'PROFESIONAL'), ('postgrado', 'POSTGRADO')], default='bachiller', max_length=40),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(choices=[('1', 'VOLUNTARIO'), ('terminacion_de_contrato', 'TERMINO DE CONTRATO'), ('periodo_de_prueba', 'PERIODO DE PRUEBA'), ('abandono_de_cargo', 'ABANDONO DE CARGO')], default='1', on_delete=django.db.models.deletion.PROTECT, to='App1.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'SOLTERO/A'), ('union_libre', 'UNIÓN LIBRE'), ('casado', 'CASADO/A'), ('divorciado', 'DIVORCIADO/A')], default='soltero/a', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='motivo_retiro',
            field=models.CharField(choices=[('1', 'VOLUNTARIO'), ('terminacion_de_contrato', 'TERMINO DE CONTRATO'), ('periodo_de_prueba', 'PERIODO DE PRUEBA'), ('abandono_de_cargo', 'ABANDONO DE CARGO')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rh',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], default='a+', max_length=3),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('cc', 'CC'), ('ti', 'TI'), ('ppt', 'PPT'), ('ce', 'CE')], default='cc', max_length=10),
        ),
    ]
