# Generated by Django 5.2.4 on 2025-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0022_alter_empleado_cargo_alter_empleado_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='jornada',
            field=models.CharField(choices=[('diurno', 'DIURNO'), ('nocturno', 'NOCTURNO'), ('virtual', 'VIRTUAL'), ('fin_de_semana', 'FIN DE SEMANA'), ('no_aplica', 'NO APLICA')], default='diurno', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='motivo_retiro',
            field=models.CharField(choices=[('voluntario', 'VOLUNTARIO'), ('terminacion_de_contrato', 'TERMINO DE CONTRATO'), ('periodo_de_prueba', 'PERIODO DE PRUEBA'), ('abandono_de_cargo', 'ABANDONO DE CARGO'), ('no_aplica', 'NO APLICA')], default='voluntario', max_length=50),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='nombre_completo_hijo',
            field=models.CharField(choices=[('core', 'Core'), ('claro_porta', 'Claro Porta')], default='core', max_length=70),
        ),
        migrations.AlterField(
            model_name='usuariosdeplataformas',
            name='usuario_plataforma_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosdeplataformas',
            name='usuario_plataforma_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosdeplataformas',
            name='usuario_plataforma_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosdeplataformas',
            name='usuario_plataforma_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosdeplataformas',
            name='usuario_plataforma_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
